version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"

  app:
    image: maheedhar429/springboot-deveops:latest
    container_name: springboot-devops-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass
    ports:
      - "8080:8080"
    depends_on:
      - mysql