spring:
  application:
    name: devops
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/worlddb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    user:
      name: maheedhar
      password: password
server:
  port: 8080
  servlet:
    context-path: /world